### ISSUE TITLE
Color transparencies - intentional effects?

### ISSUE THREAD

**Issue by mxa** [BelaPlatform/bela_sample#4]
Zooming in closer I'm discovering interesting artifacts like the teal underscore and the heading making an overprinting effect 
![grafik](https://user-images.githubusercontent.com/1220707/234988959-5f59f825-31c7-4c55-8a6e-20be2ed6991f.png)

or the bullet points having a different outline color than the fill.
![grafik](https://user-images.githubusercontent.com/1220707/234989163-366c1788-9351-400b-833d-dc9f10251cf7.png)

Are they intentional?

**Comment by disastrid** [comment]
Yes.
